{{- if .Values.ingressroute.enabled -}}
{{- $fullName := include "..fullname" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $fullName }}-websecure"
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  {{- with .Values.ingressroute.entryPoints.https }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
  {{- range .Values.ingressroute.routes }}
  - kind: Rule
    match: "Host(`{{ tpl .host $ }}`)"
    middlewares:
    {{- range .middlewares.https }}
    - name: "{{ $fullName }}-{{ .name }}"
    {{- end }}
    services:
      - kind: Service
        name: {{ $fullName }}
        namespace: {{ $namespace }}
        passHostHeader: true
        port: {{ $svcPort }}
  {{- end }}
  tls:
    secretName: "{{ $fullName }}-tls"
{{- end }}
